import {lend} from "../models/lend.model";

export class ListServices {
  books: lend[] = [
    { name: "Harry Potter",
      description: " lorem ipsum blablabla ",
      isLend: true},
    { name: "Les mystères sont de mise",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Game of Thrones",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Les 3 dumas",
      description: " lorem ipsum blablabla ",
      isLend: true},
    { name: "Tintin",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Société & Utopie",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Le vélo de police",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "La programmation pour les noobs",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Code pénal",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Science & géo",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Game of Thrones",
      description: " lorem ipsum blablabla ",
      isLend: true},
    { name: "L'anglais facile",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "La biographie de machin",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Il était une fois ...",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "blablaland",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Naruto",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Les rebelles",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Disney Tarzan",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Kid Paddle",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Marvel Spiderman",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Plantes d'intérieur",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Dessiner des mangas",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Histoire & art",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "L'orienté objet",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Cuisiner quand on est célibataire",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Combattre les maux de tête",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "L'Homéopathie guèrit elle vraiment ?",
      description: " lorem ipsum blablabla ",
      isLend: false},
  ];

  cds: lend[] = [
    { name: "Mickael Jackson",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "ACDC",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Lara Fabian",
      description: " lorem ipsum blablabla ",
      isLend: true},
    { name: "M",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Edith Piaf",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Bob Sinclar",
      description: " lorem ipsum blablabla ",
      isLend: true},
    { name: "DJ Khaled",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Evanescence",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Jonathan",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Le roi soleil",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Disney",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Julien doré",
      description: " lorem ipsum blablabla ",
      isLend: true},
    { name: "Patrick Sébastien",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Black M",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Kaaris",
      description: " lorem ipsum blablabla ",
      isLend: false},
    { name: "Booba",
      description: " lorem ipsum blablabla ",
      isLend: false},

  ];
}
